version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - webfiles:/var/www/html
    restart: always
    networks:
      - inception_network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    networks:
      - inception_network
    volumes:
      - webfiles:/var/www/html
      - database:/var/local
    env_file:
      - .env


volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/amorais-/data/database
      o: bind
  webfiles:
    driver: local
    driver_opts:
      type: none
      device: /home/amorais-/data/webfiles
      o: bind

networks:
  inception_network:
    driver: bridge