version: "3"

services:
  wordpress:
    container_name: wordpress
    build: ./wordpress
    image: wordpress
    # depends_on:
    #   - mariadb
    networks:
      - inception_network

  # mariadb:
    # container_name: mariadb
  #   build: ./mariadb
  #   image: mariadb
  #   networks:
  #     - inception_network

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    networks:
      - inception_network
    ports:
      - "443:443"

volumes:
  database:
  webfiles:

networks:
  inception_network: {}
