version: "3"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    networks:
      - inception_network
    ports:
      - "443:443"
    volumes:
      - webfiles:/var/www/html
  
  wordpress:
    container_name: wordpress
    build: ./wordpress
    image: wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - webfiles:/var/www/html
      - database:/var/local

  mariadb:
    container_name: mariadb
    build: ./mariadb
    image: mariadb
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - database:/var/local

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/amorais-/data/database
      o: bind
  webfiles:
    driver: local
    driver_opts:
      type: none
      device: /home/amorais-/data/webfiles
      o: bind

networks:
  inception_network: {}