FROM debian:buster

RUN apt-get update && apt-get install -y php-cgi php7.3 php-fpm php-mysql php-pdo php-gd php-cli php-mbstring wordpress wget tar curl bash mariadb-client

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/

RUN mkdir -p /run/php/

COPY create_wordpress.sh /usr/local/bin

RUN chmod +x /usr/local/bin/create_wordpress.sh

WORKDIR /var/www/html/

EXPOSE 9000

ENTRYPOINT [ "/usr/local/bin/create_wordpress.sh", "/usr/sbin/php-fpm7.3", "-F" ]