FROM debian:buster

RUN apt-get update && apt-get install -y mariadb-server mariadb-client

COPY ./tools/mariadb.sh /var/local/

COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

# COPY ./tools/mariadb.sql /var/local/bin

WORKDIR /var/local/

# RUN chmod +x mariadb.sql

RUN chmod +x mariadb.sh

ENTRYPOINT [ "./mariadb.sh" ]

CMD [ "mysqld", "--bind-address=0.0.0.0" ]