FROM debian:oldstable

RUN apt-get update && apt-get install -y nginx && apt-get install openssl
COPY /conf/nginx.conf /etc/nginx/nginx.conf

#ssl
RUN mkdir /etc/nginx/ssl
RUN openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -subj "/C=PT/ST=Lisboa/L=Lisboa/O=amorais-/OU=inception/CN=amorais-.42.fr" -keyout "/etc/nginx/ssl/amorais-.key" -out "/etc/nginx/ssl/amorais-.crt"
#endssl

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]