FROM debian:oldstable

RUN apt-get update && apt-get install -y php-cgi php php-fpm php-mysql php-pdo php-gd php-cli php-mbstring wordpress wget tar curl bash

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY script.sh /var/www/html

WORKDIR /var/www/html

RUN mkdir -p /run/php

RUN chmod 777 script.sh && ./script.sh

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/

EXPOSE 9000

CMD ["/usr/sbin/php-fpm7.4", "-F"]