FROM debian:oldstable

RUN apt-get update && apt-get install -y php-cgi php php-fpm wordpress wget tar curl

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY script.sh /var/www/html

WORKDIR /var/www/html

RUN chmod 777 script.sh && ./script.sh

RUN mkdir -p /run/php

COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/

CMD ["php-fpm", "-F"]