FROM debian:oldstable

RUN apt-get update && apt-get install -y mariadb-server mariadb-client

COPY ./tools/mariadb.sh /var/local/

# COPY ./tools/mariadb.sql /var/local/bin

WORKDIR /var/local/

# RUN chmod +x mariadb.sql

RUN chmod +x mariadb.sh

ENTRYPOINT [ "./mariadb.sh" ]

CMD [ "mysqld", "--bind-address=0.0.0.0" ]