FROM debian:oldstable

RUN apt-get update && apt-get install -y mariadb-server mariadb-client

COPY ./tools/mariadb.sh /var/local/bin

COPY ./tools/mariadb.sql /var/local/bin

WORKDIR /var/local/bin

RUN chmod +x mariadb.sql

RUN chmod +x mariadb.sh && ./mariadb.sh

CMD []